---
- name: playbook 
  hosts: all
  become: yes
  tasks:
  - name: i want to install wget
    apt: 
      name: get
      state: present
  - name: i want to install apache
    apt: 
      name: "{{mywebserverpackubuntu}}"
      state: latest
    when: ansible_os_family=="Ubuntu"
  - name: i want to install httpd
    yum: 
      name: "{{mywebserverpackredhat}}"
      state: latest
    when: ansible_os_family=="RedHat"